### ISSUE TITLE
Rating system

### ISSUE THREAD

**Issue by anrchen** [anrchen/353-db#14]
Implement the rating system

**Comment by anrchen** [comment]
- Searching someone s rating (One query to select all from $search variable as the user from the trip table)
- Rating someone

Database Table trip already has the attribute $rating

**Comment by anrchen** [comment]
Create tripRating table that contains: 

Create TABLE tripRating
(
TID INT ...
rider VARCHAR ...
FOREIGN KEY (TID)...
FOREIGN KEY (rider)...
)

Set up UI --> Frontend for search by member username

Create queries to show the searched member's trip

**Comment by anrchen** [comment]
Blank

**Comment by Sam-Ming** [comment]
can rate a trip and driver now
will add another page for admin to search a bad rating

**Comment by Sam-Ming** [comment]
rating system and complaint is done
Now moving on to suspend a user that has a bad rating or getting complaint
